"""empty message

Revision ID: 523e229fbb04
Revises: 23b0da054e4e
Create Date: 2016-07-08 13:15:18.705995

"""

# revision identifiers, used by Alembic.
revision = '523e229fbb04'
down_revision = '23b0da054e4e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    op.drop_table('visual_inspection_test')
    sql = """CREATE TABLE visual_inspection_test
(
    id INTEGER PRIMARY KEY NOT NULL,
    test_result_id INTEGER,
    notes VARCHAR(1000),
    tank_cover_gasket_id INTEGER,
    tank_manhole_gasket_id INTEGER,
    tank_gas_relay_id INTEGER,
    tank_oil_level_id INTEGER,
    tank_winding_temp_max REAL,
    tank_winding_temp_actual REAL,
    tank_oil_temp_max REAL,
    tank_oil_temp_actual REAL,
    tank_winding_flag BOOLEAN,
    tank_oil_flag BOOLEAN,
    tank_pressure_unit_id INTEGER,
    tank_pressure REAL,
    tank_overpressure_valve_id INTEGER,
    tank_ampling_valve_id INTEGER,
    tank_oil_pump_id INTEGER,
    tank_gas_analyser REAL,
    tank_overall_condition_id INTEGER,
    exp_tank_pipe_gasket_id INTEGER,
    exp_tank_oil_level_id INTEGER,
    exp_tank_paint_id INTEGER,
    exp_tank_overall_condition_id INTEGER,
    bushing_gasket_id INTEGER,
    bushing_oil_level_id INTEGER,
    bushing_overall_condition_id INTEGER,
    tap_changer_gasket_id INTEGER,
    tap_changer_oil_level_id INTEGER,
    tap_changer_temp_max REAL,
    tap_changer_temp_actual REAL,
    tap_changer_pressure_max REAL,
    tap_changer_pressure_actual REAL,
    tap_changer_pressure_unit_id INTEGER,
    tap_changer_tap_position REAL,
    tap_changer_overpressure_valve_id INTEGER,
    tap_changer_ampling_valve_id INTEGER,
    tap_changer_operation_counter INTEGER,
    tap_changer_counter_id INTEGER,
    tap_changer_filter_id INTEGER,
    tap_changer_overall_condition_id INTEGER,
    radiator_fan_id INTEGER,
    radiator_gasket_id INTEGER,
    radiator_overall_condition_id INTEGER,
    control_cab_connection_id INTEGER,
    control_cab_heating_id INTEGER,
    control_cab_overall_condition_id INTEGER,
    grounding_value DOUBLE PRECISION,
    grounding_connection_id INTEGER,
    misc_foundation_id INTEGER,
    misc_temp_ambiant DOUBLE PRECISION,
    misc_load DOUBLE PRECISION,
    CONSTRAINT visual_inspection_test_test_result_id_fkey FOREIGN KEY (test_result_id) REFERENCES test_result (id),
    CONSTRAINT visual_inspection_test_tank_cover_gasket_id_fkey FOREIGN KEY (tank_cover_gasket_id) REFERENCES gasket_condition (id),
    CONSTRAINT visual_inspection_test_tank_manhole_gasket_id_fkey FOREIGN KEY (tank_manhole_gasket_id) REFERENCES gasket_condition (id),
    CONSTRAINT visual_inspection_test_tank_gas_relay_id_fkey FOREIGN KEY (tank_gas_relay_id) REFERENCES gas_relay (id),
    CONSTRAINT visual_inspection_test_tank_oil_level_id_fkey FOREIGN KEY (tank_oil_level_id) REFERENCES fluid_level (id),
    CONSTRAINT visual_inspection_test_tank_pressure_unit_id_fkey FOREIGN KEY (tank_pressure_unit_id) REFERENCES pressure_unit (id),
    CONSTRAINT visual_inspection_test_tank_overpressure_valve_id_fkey FOREIGN KEY (tank_overpressure_valve_id) REFERENCES valve_condition (id),
    CONSTRAINT visual_inspection_test_tank_ampling_valve_id_fkey FOREIGN KEY (tank_ampling_valve_id) REFERENCES valve_condition (id),
    CONSTRAINT visual_inspection_test_tank_oil_pump_id_fkey FOREIGN KEY (tank_oil_pump_id) REFERENCES pump_condition (id),
    CONSTRAINT visual_inspection_test_tank_overall_condition_id_fkey FOREIGN KEY (tank_overall_condition_id) REFERENCES overall_condition (id),
    CONSTRAINT visual_inspection_test_exp_tank_pipe_gasket_id_fkey FOREIGN KEY (exp_tank_pipe_gasket_id) REFERENCES gasket_condition (id),
    CONSTRAINT visual_inspection_test_exp_tank_oil_level_id_fkey FOREIGN KEY (exp_tank_oil_level_id) REFERENCES fluid_level (id),
    CONSTRAINT visual_inspection_test_exp_tank_paint_id_fkey FOREIGN KEY (exp_tank_paint_id) REFERENCES paint_types (id),
    CONSTRAINT visual_inspection_test_exp_tank_overall_condition_id_fkey FOREIGN KEY (exp_tank_overall_condition_id) REFERENCES overall_condition (id),
    CONSTRAINT visual_inspection_test_bushing_gasket_id_fkey FOREIGN KEY (bushing_gasket_id) REFERENCES gasket_condition (id),
    CONSTRAINT visual_inspection_test_bushing_oil_level_id_fkey FOREIGN KEY (bushing_oil_level_id) REFERENCES fluid_level (id),
    CONSTRAINT visual_inspection_test_bushing_overall_condition_id_fkey FOREIGN KEY (bushing_overall_condition_id) REFERENCES overall_condition (id),
    CONSTRAINT visual_inspection_test_tap_changer_gasket_id_fkey FOREIGN KEY (tap_changer_gasket_id) REFERENCES gasket_condition (id),
    CONSTRAINT visual_inspection_test_tap_changer_oil_level_id_fkey FOREIGN KEY (tap_changer_oil_level_id) REFERENCES fluid_level (id),
    CONSTRAINT visual_inspection_test_tap_changer_pressure_unit_id_fkey FOREIGN KEY (tap_changer_pressure_unit_id) REFERENCES pressure_unit (id),
    CONSTRAINT visual_inspection_test_tap_changer_overpressure_valve_id_fkey FOREIGN KEY (tap_changer_overpressure_valve_id) REFERENCES valve_condition (id),
    CONSTRAINT visual_inspection_test_tap_changer_ampling_valve_id_fkey FOREIGN KEY (tap_changer_ampling_valve_id) REFERENCES valve_condition (id),
    CONSTRAINT visual_inspection_test_tap_changer_counter_id_fkey FOREIGN KEY (tap_changer_counter_id) REFERENCES tap_counter_status (id),
    CONSTRAINT visual_inspection_test_tap_changer_filter_id_fkey FOREIGN KEY (tap_changer_filter_id) REFERENCES tap_filter_condition (id),
    CONSTRAINT visual_inspection_test_tap_changer_overall_condition_id_fkey FOREIGN KEY (tap_changer_overall_condition_id) REFERENCES overall_condition (id),
    CONSTRAINT visual_inspection_test_radiator_fan_id_fkey FOREIGN KEY (radiator_fan_id) REFERENCES fan_condition (id),
    CONSTRAINT visual_inspection_test_radiator_gasket_id_fkey FOREIGN KEY (radiator_gasket_id) REFERENCES gasket_condition (id),
    CONSTRAINT visual_inspection_test_radiator_overall_condition_id_fkey FOREIGN KEY (radiator_overall_condition_id) REFERENCES overall_condition (id),
    CONSTRAINT visual_inspection_test_control_cab_connection_id_fkey FOREIGN KEY (control_cab_connection_id) REFERENCES connection_condition (id),
    CONSTRAINT visual_inspection_test_control_cab_heating_id_fkey FOREIGN KEY (control_cab_heating_id) REFERENCES heating_condition (id),
    CONSTRAINT visual_inspection_test_control_cab_overall_condition_id_fkey FOREIGN KEY (control_cab_overall_condition_id) REFERENCES overall_condition (id),
    CONSTRAINT visual_inspection_test_grounding_connection_id_fkey FOREIGN KEY (grounding_connection_id) REFERENCES connection_condition (id),
    CONSTRAINT visual_inspection_test_misc_foundation_id_fkey FOREIGN KEY (misc_foundation_id) REFERENCES foundation_condition (id));
    """
    op.execute(sql=sql)

def downgrade():
    op.drop_table('visual_inspection_test')
    sql = """CREATE TABLE visual_inspection_test
(
    id INTEGER PRIMARY KEY NOT NULL,
    test_result_id INTEGER,
    notes VARCHAR(1000),
    tank_cover_gasket INTEGER,
    tank_manhole_gasket INTEGER,
    tank_gas_relay INTEGER,
    tank_oil_level INTEGER,
    tank_winding_temp_max REAL,
    tank_winding_temp_actual REAL,
    tank_oil_temp_max REAL,
    "tank_Oil_temp_actual" REAL,
    tank_winding_flag BOOLEAN,
    tank_oil_flag BOOLEAN,
    tank_pressure_unit INTEGER,
    tank_pressure REAL,
    tank_overpressure_valve INTEGER,
    tank_ampling_valve INTEGER,
    tank_oil_pump INTEGER,
    tank_gas_analyser REAL,
    tank_overall_condition INTEGER,
    exp_tank_pipe_gasket INTEGER,
    exp_tank_oil_level INTEGER,
    exp_tank_paint INTEGER,
    exp_tank_overall_condition INTEGER,
    bushing_gasket INTEGER,
    bushing_oil_level INTEGER,
    bushing_overall_condition INTEGER,
    tap_changer_gasket INTEGER,
    tap_changer_oil_level INTEGER,
    tap_changer_temp_max REAL,
    tap_changer_temp_actual REAL,
    tap_changer_pressure_max REAL,
    tap_changer_pressure_actual REAL,
    tap_changer_pressure_unit INTEGER,
    tap_changer_tap_position REAL,
    tap_changer_overpressure_valve INTEGER,
    tap_changer_ampling_valve INTEGER,
    tap_changer_operation_counter INTEGER,
    tap_changer_counter INTEGER,
    tap_changer_filter INTEGER,
    tap_changer_overall_condition INTEGER,
    radiator_fan INTEGER,
    radiator_gasket INTEGER,
    radiator_overall_condition INTEGER,
    control_cab_connection INTEGER,
    control_cab_heating INTEGER,
    control_cab_overall_condition INTEGER,
    grounding_value DOUBLE PRECISION,
    grounding_connection INTEGER,
    misc_foundation INTEGER,
    misc_temp_ambiant DOUBLE PRECISION,
    misc_load DOUBLE PRECISION,
    CONSTRAINT visual_inspection_test_test_result_id_fkey FOREIGN KEY (test_result_id) REFERENCES test_result (id),
    CONSTRAINT visual_inspection_test_tank_cover_gasket_fkey FOREIGN KEY (tank_cover_gasket) REFERENCES gasket_condition (id),
    CONSTRAINT visual_inspection_test_tank_manhole_gasket_fkey FOREIGN KEY (tank_manhole_gasket) REFERENCES gasket_condition (id),
    CONSTRAINT visual_inspection_test_tank_gas_relay_fkey FOREIGN KEY (tank_gas_relay) REFERENCES gas_relay (id),
    CONSTRAINT visual_inspection_test_tank_oil_level_fkey FOREIGN KEY (tank_oil_level) REFERENCES fluid_level (id),
    CONSTRAINT visual_inspection_test_tank_pressure_unit_fkey FOREIGN KEY (tank_pressure_unit) REFERENCES pressure_unit (id),
    CONSTRAINT visual_inspection_test_tank_overpressure_valve_fkey FOREIGN KEY (tank_overpressure_valve) REFERENCES valve_condition (id),
    CONSTRAINT visual_inspection_test_tank_ampling_valve_fkey FOREIGN KEY (tank_ampling_valve) REFERENCES valve_condition (id),
    CONSTRAINT visual_inspection_test_tank_oil_pump_fkey FOREIGN KEY (tank_oil_pump) REFERENCES pump_condition (id),
    CONSTRAINT visual_inspection_test_tank_overall_condition_fkey FOREIGN KEY (tank_overall_condition) REFERENCES overall_condition (id),
    CONSTRAINT visual_inspection_test_exp_tank_pipe_gasket_fkey FOREIGN KEY (exp_tank_pipe_gasket) REFERENCES gasket_condition (id),
    CONSTRAINT visual_inspection_test_exp_tank_oil_level_fkey FOREIGN KEY (exp_tank_oil_level) REFERENCES fluid_level (id),
    CONSTRAINT visual_inspection_test_exp_tank_paint_fkey FOREIGN KEY (exp_tank_paint) REFERENCES paint_types (id),
    CONSTRAINT visual_inspection_test_exp_tank_overall_condition_fkey FOREIGN KEY (exp_tank_overall_condition) REFERENCES overall_condition (id),
    CONSTRAINT visual_inspection_test_bushing_gasket_fkey FOREIGN KEY (bushing_gasket) REFERENCES gasket_condition (id),
    CONSTRAINT visual_inspection_test_bushing_oil_level_fkey FOREIGN KEY (bushing_oil_level) REFERENCES fluid_level (id),
    CONSTRAINT visual_inspection_test_bushing_overall_condition_fkey FOREIGN KEY (bushing_overall_condition) REFERENCES overall_condition (id),
    CONSTRAINT visual_inspection_test_tap_changer_gasket_fkey FOREIGN KEY (tap_changer_gasket) REFERENCES gasket_condition (id),
    CONSTRAINT visual_inspection_test_tap_changer_oil_level_fkey FOREIGN KEY (tap_changer_oil_level) REFERENCES fluid_level (id),
    CONSTRAINT visual_inspection_test_tap_changer_pressure_unit_fkey FOREIGN KEY (tap_changer_pressure_unit) REFERENCES pressure_unit (id),
    CONSTRAINT visual_inspection_test_tap_changer_overpressure_valve_fkey FOREIGN KEY (tap_changer_overpressure_valve) REFERENCES valve_condition (id),
    CONSTRAINT visual_inspection_test_tap_changer_ampling_valve_fkey FOREIGN KEY (tap_changer_ampling_valve) REFERENCES valve_condition (id),
    CONSTRAINT visual_inspection_test_tap_changer_counter_fkey FOREIGN KEY (tap_changer_counter) REFERENCES tap_counter_status (id),
    CONSTRAINT visual_inspection_test_tap_changer_filter_fkey FOREIGN KEY (tap_changer_filter) REFERENCES tap_filter_condition (id),
    CONSTRAINT visual_inspection_test_tap_changer_overall_condition_fkey FOREIGN KEY (tap_changer_overall_condition) REFERENCES overall_condition (id),
    CONSTRAINT visual_inspection_test_radiator_fan_fkey FOREIGN KEY (radiator_fan) REFERENCES fan_condition (id),
    CONSTRAINT visual_inspection_test_radiator_gasket_fkey FOREIGN KEY (radiator_gasket) REFERENCES gasket_condition (id),
    CONSTRAINT visual_inspection_test_radiator_overall_condition_fkey FOREIGN KEY (radiator_overall_condition) REFERENCES overall_condition (id),
    CONSTRAINT visual_inspection_test_control_cab_connection_fkey FOREIGN KEY (control_cab_connection) REFERENCES connection_condition (id),
    CONSTRAINT visual_inspection_test_control_cab_heating_fkey FOREIGN KEY (control_cab_heating) REFERENCES heating_condition (id),
    CONSTRAINT visual_inspection_test_control_cab_overall_condition_fkey FOREIGN KEY (control_cab_overall_condition) REFERENCES overall_condition (id),
    CONSTRAINT visual_inspection_test_grounding_connection_fkey FOREIGN KEY (grounding_connection) REFERENCES connection_condition (id),
    CONSTRAINT visual_inspection_test_misc_foundation_fkey FOREIGN KEY (misc_foundation) REFERENCES foundation_condition (id));
    """
    op.execute(sql=sql)